<!DOCTYPE html>
<html class="no-js" lang="">
  <head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145358157-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-145358157-1');
    </script>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
      Notes
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="shortcut icon" href="favicon.ico"/>
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,800&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
      integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/dist/css/sloth.min.css">
  </head>
  <body>
    <nav>
      <a href="index.html">
        <img src="apple-touch-icon.png"/>
        <b>django_dna</b>
      </a>
      <br/>
      <br/>
      <menu>
              <a href="/eliothing">
                <img src="/eliothing/apple-touch-icon.png"/>
                <b>eliothing</b>
              </a>
            <label>Python</label>
            <nav>
                  <a href="/eliothing/banjo">
                    <img src="/eliothing/banjo/apple-touch-icon.png"/>
                    <b>banjo</b>
                  </a>
            </nav>
      </menu>
    </nav>
    <h1 id="notes">Notes</h1>
<p>In an earlier version, the DJANGO_FIELDS dictionary in <code>dna.py</code> was global to the module. Problem was when a model field type was accessed more than once this creates a issue during migrate and migration.</p>
<p>For instance:</p>
<pre><code class="language-bash">elio_riff.Thing.sameAs: (models.E006) The field &#39;sameAs&#39; clashes with the field &#39;sameAs&#39; from model &#39;elio_riff.thing&#39;.
elio_riff.Thing.sameAs: (models.E006) The field &#39;sameAs&#39; clashes with the field &#39;sameAs&#39; from model &#39;elio_riff.thing&#39;.
elio_riff.Thing.sameAs: (models.E006) The field &#39;sameAs&#39; clashes with the field &#39;sameAs&#39; from model &#39;elio_riff.thing&#39;.
elio_riff.Thing.sameAs: (models.E006) The field &#39;sameAs&#39; clashes with the field &#39;sameAs&#39; from model &#39;elio_riff.thing&#39;.</code></pre>
<p>The explanation for these errors is that 4 fields were using the same <em>instance</em> of <code>models.URLField</code>.</p>
<p>Moving the DJANGO_FIELDS inside the <code>django_type_of</code> method fixed this problem and the whole thing only took about 8 hours to work out.</p>
    <footer>
      <a href="https://gitlab.com/elioway/eliothing/django_dna">GitLab</a> |
      <a href="https://gitlab.com/eliothing">Contribute</a>
      <img src="elio-django_dna-logo.png">
      <label>&copy; 2019 Made the elioWay</label>
    </footer>
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
      crossorigin="anonymous"></script>
    <script src="/dist/js/adons.js"></script>
    <script src="/dist/js/main.js"></script>
  </body>
</html>
